os:
  - linux
services:
  - docker
env:
  matrix:
    - APP=alerter
    - APP=console
    - APP=elasticsearch
    - APP=logstash
    - APP=zipkin
    - APP=import-dashboards
    - APP=curator
install:
  - docker version
  - docker build -f crawlerbot-"$APP"/Dockerfile -t crawlerbot/crawlerbot-"$APP":travis crawlerbot-"$APP"/
script:
  - docker images
  - docker inspect crawlerbot/crawlerbot-"$APP":travis
